raven-configure almost working; need to sed now
Changed home-manager/master/default.nix to have one line for pattern,
instead of multiple lines in which on is commented out.

diff --git a/raven-configure b/raven-configure
--- a/raven-configure
+++ b/raven-configure
@@ -1,71 +1,184 @@
 #!/usr/bin/env bash
-# This script checks for missed REPLACEME's
+# This script interactively walks a user through configuring the Raven template.
 
-set -euo pipefail
+function usage
+{
+    >&2 cat << EOF
+Usage: $0
+   [ --check ]
+   [ --profile=profile-path]
+   [ -h | --help ]
+
+check will simply check for missed values.
+
+profile-path can specify a file which contains values which will then be skipped
+during the interactive prompts. These values are...
+
+RAVEN_HOSTNAME=
+RAVEN_PATTERN=
+RAVEN_GIT_USERNAME=
+RAVEN_GIT_EMAIL=
+RAVEN_TIMEZONE=
+RAVEN_LOCALE=
+RAVEN_TARGET_DISK=
+
+Values set in this way will not take effect if the respective .nix files have already
+had their "REAPLACEME_*" texts modified.
+
+EOF
+}
+
+function check
+{
+    echo "Checking for any missed REPLACEME's..." >&2
+    echo
+    
+    grep -r REPLACEME_ | grep -v .swp | grep -v ^.git | grep -v docs | grep -v raven-configure
+    if [ $? == 0 ]
+    then
+        echo ""
+        echo "You missed REPLACEME's in the above files. Don't try to install yet." >&2
+        return 1
+    else
+        echo "You've hit all REPLACEME's. If you did those right then you should be good to use raven!" >&2
+        return 0
+    fi
+}
+
+set -eo pipefail
 
 SCRIPT_PATH=$(readlink -f "$0")
 SCRIPT_DIR=$(dirname "$SCRIPT_PATH")
 
 cd $SCRIPT_DIR
 
-echo "Checking for any missed REPLACEME's..." >&2
-echo
+args=$(getopt -o h --long help,check,profile: -- "$@")
+if [[ $? -gt 0 ]]; then
+    usage
+fi
 
-grep -r REPLACEME_ | grep -v .swp | grep -v ^.git | grep -v docs
-if [ $? == 0 ]
-then
-    echo ""
-    echo "You missed REPLACEME's in the above files. Don't try to install yet." >&2
-else
-    echo "You've hit all REPLACEME's. If you did those right then you should be good to use raven!" >&2
+eval set -- ${args}
+while :
+do
+    case $1 in
+    --check)
+        check
+        exit $?
+        shift
+        ;;
+    --profile)
+        source $2
+        shift 2
+        ;;
+    -h | --help)
+        usage
+        exit 0
+        shift
+        ;;
+    # -- means the end of the arguments; drop this, and break out of the while loop
+    --)
+        shift
+        break ;;
+    *)
+        >&2 echo Unsupported option: $1
+        usage
+        exit 1
+        ;;
+    esac
+done
+
+# This command finds the lines in Raven that need replacing
+REPLACEMES="$(grep -r REPLACEME_ | grep -v .swp | grep -v ^.git | grep -v docs | grep -v raven-configure)"
+
+if ! command -v gum >/dev/null 2>&1 || ! command -v jq >/dev/null 2>&1; then
+    echo "ERROR: This script requires gum and jq to be installed. Run 'nix-shell -p gum jq' and then re-run."
+    exit 1
 fi
 
 if [ "$(id -u)" -eq 0 ]; then
-    gum confirm --default=false "WARNING: You shouldn't use run this script as the root user. Proceed Anyway? "
+    echo "ERROR: Don't run this script as the root user."
+    exit 1
 fi
-
-if [ ! -d "$HOME" ]
-then
-    gum confirm --default=false "ERROR: For some reason $HOME doesn't exist for user $(whoami). Create it? "
-fi
-
-if [ ! -d "$HOME/raven-machines" ]; then
-    git clone https://github.com/digital-raven/raven.git "$HOME/raven-machines"
-fi
-
-cd $HOME/raven-machines
 
 # Select hostname
-HOSTNAME=$(gum input --prompt "What will you name your AC? " --placeholder "nightfall")
+if [[ "$REPLACEMES" =~ "REPLACEME_hostName" ]] && [ -z "$RAVEN_HOSTNAME" ]
+then
+    RAVEN_HOSTNAME=$(gum input --prompt "What will you name your AC? " --placeholder "nightfall")
+fi
 
-        # Git username and email
-        if gum confirm --default=false "(Optional) Enter name and email you use for git commits?; then
-          GIT_USERNAME=$(gum input --prompt "Enter your name for git commits: ") --placeholder "Raven"
-          GIT_EMAIL=$(gum input --prompt "Enter your email for git commits: ") --placeholder "raven@rubicon.aleeas.com"
-        fi
+if [ -z "$RAVEN_HOSTNAME" ]
+then
+    echo "ERROR: You must name your AC."
+    exit 1
+fi
 
-        # Select timezone
-        TIMEZONE=timedatectl list-timezones | gum choose --height=30
+# Raven pattern selection
+if [[ "$REPLACEMES" =~ "REPLACEME_raven-pattern" ]] && [ -z "$RAVEN_PATTERN" ]
+then
+    RAVEN_PATTERN=$(ls patterns | grep -v raven-iso | grep -v README.md | gum choose --header "Select which Raven pattern you want to install")
+fi
 
-        # Select locale
-        LOCALE="en_US.UTF-8"
-        if gum confirm --default=false "Select a locale other than $LOCALE? "; then
-          LOCALE=$(wget -qO - 'https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=localedata/SUPPORTED' | sed -s 's/\\//' | tail -n +4 | gum choose --height=40 --header="Supported Locales")
-        fi
+# Git username and email
+if [[ "$REPLACEMES" =~ "REPLACEME_gitUserName" ]] && [ -z "$RAVEN_GIT_USERNAME" ]
+then
+    if gum confirm --default=false "(Optional) Enter name and email you use for git commits"
+    then
+        RAVEN_GIT_USERNAME=$(gum input --prompt "Enter your name for git commits: " --placeholder "Raven")
+        RAVEN_GIT_EMAIL=$(gum input --prompt "Enter your email for git commits: " --placeholder "raven@rubicon.aleeas.com")
+    fi
+fi
 
-        # Disk selection
-        sda_devices="$(lsblk -JpS -o NAME,VENDOR,MODEL,REV,SERIAL,SIZE)"
-        nvme_devices="$(lsblk -JpN -o NAME,VENDOR,MODEL,REV,SERIAL,SIZE)"
+# Select timezone
+if [[ "$REPLACEMES" =~ "REPLACEME_timeZone" ]]
+then
+    RAVEN_TIMEZONE=$(timedatectl list-timezones | gum choose --header "Select your timezone" --height=30)
+fi
 
-        TARGET_DISK=$(echo "$sda_devices" \
-          "$nvme_devices" | jq -s '[.[].blockdevices[]] | map({name, vendor, model, rev, serial, size})' | jq -r '(.[0] | keys_unsorted) as $keys | $keys, map([.[ $keys[] ]])[] | @csv' | gum table) | awk -F, '{print $1}'
+# Select locale
+if [[ "$REPLACEMES" =~ "REPLACEME_defaultLocale" ]]
+then
+    RAVEN_LOCALE="en_US.UTF-8"
+    if gum confirm --default=false "Select a locale other than $RAVEN_LOCALE? "; then
+        LOCALE=$(wget -qO - 'https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=localedata/SUPPORTED' | sed -s 's/\\//' | tail -n +4 | gum choose --height=40 --header="Supported Locales")
+    fi
+fi
 
-        gum confirm  --default=false \
-          "This will erase $TARGET_DISK and format it for Raven. Is this correct?"
+# Disk selection
+sda_devices="$(lsblk -JpS -o NAME,VENDOR,MODEL,REV,SERIAL,SIZE)"
+nvme_devices="$(lsblk -JpN -o NAME,VENDOR,MODEL,REV,SERIAL,SIZE)"
 
-        echo "Partitioning Disks"
-        sudo nix run github:nix-community/disko \
-        --extra-experimental-features "nix-command flakes" \
-        --no-write-lock-file \
-        -- \
-        --mode zap_create_mount \
+RAVEN_TARGET_DISK=$(echo "$sda_devices" \
+    "$nvme_devices" | jq -s '[.[].blockdevices[]] | map({name, vendor, model, rev, serial, size})' | jq -r '(.[0] | keys_unsorted) as $keys | $keys, map([.[ $keys[] ]])[] | @csv' | gum table | awk -F, '{print $1}')
+
+confirm_text="You've specified
+
+AC name:     $RAVEN_HOSTNAME
+pattern:     $RAVEN_PATTERN
+git-name:    $RAVEN_GIT_USERNAME
+git-email:   $RAVEN_GIT_EMAIL
+time-zone:   $RAVEN_TIMEZONE
+locale:      $RAVEN_LOCALE
+
+target disk: $RAVEN_TARGET_DISK
+
+Is this correct?
+"
+
+gum confirm --default=false "$confirm_text"
+
+# Copy the lines that start with "boot." from /etc/nixos/configuration.nix
+BOOT_SETTINGS="$(grep "^ \+boot\." /etc/nixos/configuration.nix)"
+
+# Hardware configuration
+echo "Generating hardware configuration to ./host/hardware-configuration.nix"
+nixos-generate-config --show-hardware-config > host/hardware-configuration.nix
+
+#gum confirm  --default=false \
+#    "This will erase $TARGET_DISK and format it for Raven. Is this correct?"
+#
+#echo "Partitioning Disks"
+#sudo nix run github:nix-community/disko \
+#    --extra-experimental-features "nix-command flakes" \
+#    --no-write-lock-file \
+#    -- \
+#    --mode zap_create_mount \
